<?php

# ISS AQUI VAI SERVIR PARA USARMOS PARA CONECTAR A PARTE PRINCIPAL COM OUTRAS PARTES. EX: CONECTAR O PHP COM O CSS;
# NOS DIZ AONDE É A RAÍZ DO NOSSO SISTEMA
# NOS AJUDA A LINKAR O PHP COM AS IMAGENS, COM O CSS, ETC.
# PODEMOS USAR ELE AONDE DESEJARMOS. BASTA IMPORTÁ-LO AO LUGAR DESEJADO;
  $BASE_URL = "http://" . $_SERVER['SERVER_NAME'] . dirname($_SERVER['REQUEST_URI'] . '?') . '/';